"""add_repository_files_and_analyses

Revision ID: 248a1cdbee97
Revises: 85bb31a7cdaa
Create Date: 2026-07-05 12:48:42.103589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '248a1cdbee97'
down_revision: Union[str, None] = '85bb31a7cdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_analyses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('architecture_summary', sa.Text(), nullable=True),
    sa.Column('architecture_style', sa.String(length=64), nullable=True),
    sa.Column('architecture_layers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repo_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repo_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_analyses_repository_id'), 'repository_analyses', ['repository_id'], unique=False)
    op.create_table('repository_files',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_files_repository_id'), 'repository_files', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_files_repository_id'), table_name='repository_files')
    op.drop_table('repository_files')
    op.drop_index(op.f('ix_repository_analyses_repository_id'), table_name='repository_analyses')
    op.drop_table('repository_analyses')
    # ### end Alembic commands ###
