"""remove cost_usd column

Revision ID: 30abd9758e60
Revises: b8261a605512
Create Date: 2026-07-05 14:15:26.927329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30abd9758e60'
down_revision: Union[str, None] = 'b8261a605512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_analyses', 'cost_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_analyses', sa.Column('cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###
