"""add_progress_to_repositories

Revision ID: 885ef361c0e5
Revises: 311d91274456
Create Date: 2026-07-04 15:13:16.171161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885ef361c0e5'
down_revision: Union[str, None] = '311d91274456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('progress', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'progress')
    # ### end Alembic commands ###
