"""add analysis reliability columns

Revision ID: b8261a605512
Revises: 248a1cdbee97
Create Date: 2026-07-05 14:11:43.130733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8261a605512'
down_revision: Union[str, None] = '248a1cdbee97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_analyses', sa.Column('error_code', sa.String(length=64), nullable=True))
    op.add_column('repository_analyses', sa.Column('cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_analyses', 'cost_usd')
    op.drop_column('repository_analyses', 'error_code')
    # ### end Alembic commands ###
